import type { Metadata } from "next";
import "./global.css";


export const metadata: Metadata = {
  title: "Valentine pookie",
  description: "Generated by Vadym",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="rus">
      <body>{children}</body>
    </html>
  );
}
